### ISSUE TITLE
Alimenter le GET /me avec les infos de l'utilisteur

### ISSUE THREAD

**Issue by bchollet** [PDG2023/GameSync.App#103]
Au démarrage de l'application, il faut envoyer le jwt contenu dans le localstorage à l'API pour que cette dernière puisse récupérer les informations de l'utilisateurs OU le déconnecter si le jwt n'est plus valide.

Le endpoint existe, mais il ne retourne pas les infos de l'utilisateurs:

![image](https://github.com/PDG2023/GameSync.App/assets/43602096/a453bfb7-732f-4aef-984a-a48e77dd32ab)

**Comment by KevinFerati** [comment]
Quelles informations doivent être retournées ?

**Comment by bchollet** [comment]
@KevinFerati, je te propose: 
- email
- nom d'utilisateur

L'utilisateur ne possède pas d'autres champs utile pour l'application.
