### ISSUE TITLE
Ajouter un disciminant pour identifier l'id d'un jeu d'une collection de celui d'un résultat de recherche

### ISSUE THREAD

**Issue by bchollet** [PDG2023/GameSync.App#107]
On utilise un seul composant pour afficher le détail d'un jeu, mais il ne sait pas quel call HTTP faire pour récupérer les détails d'un jeu:
- Est-ce un jeu avec un id de BGG ?
- Est-ce un jeu custom avec son propre id ?

**Comment by bchollet** [comment]
@KevinFerati, j'ai fait un micmac en changeant le chemin pour identifier quel endpoint appeler. C'est moche, mais fonctionnel. Je te laisse fermer l'issue si tu ne comptes pas faire de développement.

![image](https://github.com/PDG2023/GameSync.App/assets/43602096/5431c576-d98c-42c9-9e1e-720382ddb2d5)

**Comment by bchollet** [comment]
Voici un autre use-case:
- Un jeu custom ne doit pas pouvoir être modifiable dans la collection. Le discriminant permettrait de configurer ceci.

![image](https://github.com/PDG2023/GameSync.App/assets/43602096/cac72472-6ec6-4da8-8a90-10e241158f00)

**Comment by kjorand** [comment]
J'aurais bien vu un unique endpoint ... avec un discriminant dans le retour ... (et juste la petite variation dans l'affichage ... )

Mais peut-être qu'il me manque juste un peu de contexte pour comprendre que c'est une idée de merde ...

**Comment by KevinFerati** [comment]
> J'aurais bien vu un unique endpoint ... avec un discriminant dans le retour ... (et juste la petite variation dans l'affichage ... )
> 
> Mais peut-être qu'il me manque juste un peu de contexte pour comprendre que c'est une idée de merde ...

L'endpoint unique est difficilement applicable. Supposons l'endpoint /games/32 : Comment savoir si 32 est un identifiant pour un jeu de la collection personnelle de l'utilisateur ou celui d'un jeu de BGG? Une des solutions serait de mettre la source que l'on souhaite dans l'endpoint, ce que je fais au travers de la sépéaration des endpoints et de la logique.

> On utilise un seul composant pour afficher le détail d'un jeu, mais il ne sait pas quel call HTTP faire pour récupérer les détails d'un jeu:
> 
> * Est-ce un jeu avec un id de BGG ?
> * Est-ce un jeu custom avec son propre id ?

Je pense que c'est un problème de front, plutôt. Il existe bien 2 endpoints permettant d'avoir ce qu'il faut, avec /api/games/{id} pour les détails des jeux BGG et /users/me/[...] pour ceux de collection perso.

**Comment by KevinFerati** [comment]
J'ai ajouté un bool "IsCustom" dans les retours de l'endpoint de la collection
