### ISSUE TITLE
Identifier si un jeu du catalogue est déjà présent dans la collection de l'utilisateur

### ISSUE THREAD

**Issue by bchollet** [PDG2023/GameSync.App#109]
J'aimerai afficher de façon conditionnelle un bouton permettant d'ajouter ou de retirer un jeu de sa collection. Cette condition dépend de si le jeu est présent ou non dans la collection de l'utilisateur.

![image](https://github.com/PDG2023/GameSync.App/assets/43602096/d58d71c3-03f9-49b5-ae04-c68233b74d45)

Faut-il un nouveau endpoint ou gérer les jeux BGG différemment dans la collection ?

**Comment by KevinFerati** [comment]
Je ferai les modifs back et front pour ajouter un élément indiquant si le jeu est présent dans une collection
