### ISSUE TITLE
Code HTML des caractères spéciaux au lieu de leur interprétation ...

### ISSUE THREAD

**Issue by kjorand** [PDG2023/GameSync.App#114]
Code HTML des caractères spéciaux au lieu de leur interprétation ...
Pas sûr si ça vient de l'API dans laquelle on tape ... ou si c'est de notre part : 
![image](https://github.com/PDG2023/GameSync.App/assets/25977492/4fe6a6c1-9d57-4ec8-8cf2-e493dd38a7c2)

EDIT : 
Probablement de l'API des jeux/la manière dont on la traite :
![image](https://github.com/PDG2023/GameSync.App/assets/25977492/9222a429-dbe7-4d6c-8658-3b103aac8330)

_Originally posted by @kjorand in https://github.com/PDG2023/GameSync.App/issues/112#issuecomment-1703779241_

**Comment by KevinFerati** [comment]
Duplicat de : #95
