### ISSUE TITLE
Possibilité d'avoir une image pour les jeux perso ?

### ISSUE THREAD

**Issue by kjorand** [PDG2023/GameSync.App#125]
![image](https://github.com/PDG2023/GameSync.App/assets/25977492/5640bbe1-e296-40d8-85c8-a98f1d5d739d)

**Comment by bchollet** [comment]
Les images sont un processus excessivement relou à gérer en architecture REST. 
Pour le bien de notre santé mentale, nous mettons ce point de côté.
Peut-être qu'on autorisera un `imageUrl` mais ce n'est pas la priorité

**Comment by KevinFerati** [comment]
Il aurait également fallu que je fasse une logique de stockage d'image  différentes selon l'environnemnet (local ou sur le cloud) donc je préfère faire autre chose
