### ISSUE TITLE
Régression : màj du "login" plus effectif ?

### ISSUE THREAD

**Issue by kjorand** [PDG2023/GameSync.App#126]
En étant connecté, on a  :

![image](https://github.com/PDG2023/GameSync.App/assets/25977492/4c2d6619-5bc5-49a2-83fa-c881d9e7b9f5)

Au lieu du nom d'utilisateur, comme ça avait été corrigé par le passé ...

**Comment by bchollet** [comment]
Le problème vient de la #103 

Je ferme l'issue
