### ISSUE TITLE
Ajout du bouton de suppression de la collection pour les jeux perso

### ISSUE THREAD

**Issue by kjorand** [PDG2023/GameSync.App#127]
Le bouton n'apparait que sur la liste de collection ... et pas sur le jeu, contrairement aux jeux "normaux" : 

![image](https://github.com/PDG2023/GameSync.App/assets/25977492/dbd2fa03-61fc-45e7-99fc-8e89eb300806)

**Comment by bchollet** [comment]
Ce comportement est voulu. Il n'est pas prévu de le modifier.

Je ferme l'issue
