### ISSUE TITLE
Going to invalid URL during navigation

### ISSUE THREAD

**Issue by kjorand** [PDG2023/GameSync.App#25]
En cliquant sur :
![image](https://github.com/PDG2023/GameSync.App/assets/25977492/431c8086-7036-4a56-88cd-eeebfda22879)

On "arrive" à :
https://gamesync.azurewebsites.net/parties

(affiché dans la barre d'adresse) 
... 
Sauf que le serveur n'est pas capable de la traiter => 404 si on rentre l'adresse ... ou si on refresh

**Comment by bchollet** [comment]
Angular utilise le routage côté client (client-side routing), ce qui signifie que les routes sont gérées par le JavaScript de l'application et non par le serveur. Lorsqu'on accède à des routes spécifiques comme "/login" dans l'application, Angular les traite au niveau du navigateur. Cependant, lorsque qu'on rafraichît la page, le navigateur envoie une requête au serveur pour cette URL spécifique, et si le serveur ne sait pas comment gérer cette URL, une erreur 404 est renvoyée
