### ISSUE TITLE
Création de soirées

### ISSUE THREAD

**Issue by Fl4gu1z0wsky** [PDG2023/GameSync.App#83]

**Comment by kjorand** [comment]
@bchollet Est-ce que tu as des requirements particuliers ?

Je dirais qu'une soirée :
- est organisée à ***une date*** (est-ce qu'on doit pouvoir la voter, la date ou uniquement le créateur la fixe ? ... si on choisit que seul le créateur la fixe, est-ce qu'on garde en tête l'idée d'éventuellement implémenter le vote plus tard ? [juste éviter les trucs qui pourraient bloquer cette possibilité ...] )
- comprend une ***liste d'invités*** (permet de lister qui a répondu présent parmi les invités ? directement lié au vote pour les jeux ?)
- est associée à une ***liste de jeux*** proposés (prendre automatiquement la collection de l'organisateur ? Donner une possibilité d'en ajouter d'autres [genre pour ce week-end mon frère est chez moi ... donc y a nos deux collections à dispo ?] )
- permet de ***vote***r pour son/ses ***jeux*** préférés parmi ceux proposés (vote triple ? [envie d'y jouer, neutre, pas envie ... permet de garder l'éventualité de la fonctionnalité "tinder-like" : swipe à : gauche, bas, droite] )
- ... autre ?

**Comment by KevinFerati** [comment]
Cette issue est pour la création de soirées uniquement, les Invitations et les votes étant dans une autre issue epic

Une partie de tes questions peut être répondues en regardant le CDC (2.5 et 2.6)

- Concernant le vote "neutre", ce serait juste ne pas voter 
- je ne pense pas que "Tinder-Like" serait pertinent ici  car c'est un affichage qui est OK dans les cas où tu ne peux pas / n'a pas besoin de revenir en arrière. Ici, on devrait pouvoir avoir une vue globale sur tous les jeux proposés dans une soirée
