### ISSUE TITLE
Comportement étrange du loader

### ISSUE THREAD

**Issue by kjorand** [PDG2023/GameSync.App#99]
Comportement étrange du loader 

Steps to reproduce :

1. Rechercher un jeu (affiché en bas de la capture ci-dessous)
2. Cliquer le jeu pour l'afficher
3. Rechercher un nouveau (pas dans le cache)
4. => apparaissent alors 2 spiners :

![image](https://github.com/PDG2023/GameSync.App/assets/25977492/ed172755-fc45-4a79-a699-e3ae377f45e2)

Voilà voilà ...

_Originally posted by @kjorand in https://github.com/PDG2023/GameSync.App/issues/98#issuecomment-1696247546_

**Comment by bchollet** [comment]
@kjorand, j'ai remplacé le spinner par une progress bar... Ca ne règle pas le problème en soit, mais c'est peut-être moins choquant d'un point de vue UX. Tu me redirais ce que tu en penses.

Je ferme l'issue

**Comment by kjorand** [comment]
C'est ... excellent !!!
